### ISSUE TITLE
Is it supposed to look like this?

### ISSUE THREAD

**Issue by OsakiTsukiko** [FlorianMichael/fabric-imgui-example-mod#13]
Endeavour OS (Arch Linux based) 
Kernel: 6.12.1-arch1-1
CPU: AMD Ryzen 7 6800H with Radeon Graphics (16) @ 4.785GHz
GPU: AMD ATI Radeon 680M
GPU: NVIDIA GeForce RTX 3050 Mobile

![image](https://github.com/user-attachments/assets/96a0db6e-7157-4420-89d5-08847c6aff06)

**Comment by jessec** [comment]
I have seen this too I changed jdk's and sometimes it's good but most of the time it crashes.

**Comment by jessec** [comment]
I upgraded and this solves it for me: imgui_version=1.87.7

**Comment by florianreuth** [comment]
Should be fixed now in the latest commit, thanks @jessec
