### ISSUE TITLE
net.minecraft.client.util.Window import does not exist on Minecraft Version 1.21

### ISSUE THREAD

**Issue by tobiazsh** [FlorianMichael/fabric-imgui-example-mod#8]
In file `MinecraftClientMixin.java`, `import net.minecraft.client.util.Window;` does not exist. I am running Minecraft Version 1.21. Has anyone else experienced this error? And how do I fix it? Thanks!

**Comment by florianreuth** [comment]
Sounds like you have setuped the project wrong, can you show a picture of the class?

**Comment by tobiazsh** [comment]
I did not expect this fast response lol xD. But I just went back to it and I was just stupid. I put the MinecraftClientMixing in the Main half. Thanks tho!
